# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci-casper-js-sdk

on:
  push:
    branches: [ master, feature/gh-actions-fixes ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14.x]

    steps:
    - name: Test
      run: |
        echo ${{github.ref}}
        if [[ ${{ github.ref }} == 'refs/heads/feature/gh-actions-fixes']]; then
          echo "Hello World"
        else
          echo "Wrong branch"
        fi
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Build & Test üîß
      run: | 
        npm install
        npm test
        npm run docs
    - name: Deploy Docs üöÄ
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/ # The folder that the typedoc generates files.
        CLEAN: true # Automatically remove deleted files from the deploy branch
