# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci-casper-js-sdk

on:
  push:
    branches: [ master, next ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master, next ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14.x]

    steps:
    - name: Set release tag
      run: |
        echo ${{ github.ref }}
        if [ ${{ github.ref }} == 'refs/heads/legacy' ]; then
          echo "release_tag=legacy" >> $GITHUB_ENV

        else
          echo "release_tag=latest" >> $GITHUB_ENV
        fi
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Build & Test ğŸ”§
      run: | 
        npm install
        npm test
        npm run docs
    - name: Deploy Docs ğŸš€
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/ # The folder that the typedoc generates files.
        TARGET_FOLDER: ${{ env.release_tag }}
        CLEAN: true # Automatically remove deleted files from the deploy branch
